DROP TABLE IF EXISTS SPECIALIST;

CREATE TABLE SPECIALIST
(
   id INT AUTO_INCREMENT PRIMARY KEY,
   type VARCHAR (250) NOT NULL,
   name VARCHAR (250) NOT NULL,
   available_day VARCHAR (250) DEFAULT NULL,
   available_time VARCHAR (250) DEFAULT NULL,
   is_available VARCHAR (1) DEFAULT NULL,
   hospital_id INT
);